defaults:
  - _self_
  - dataset: arc-easy

output_dir: outputs/eval
global_seed: 31337 
local_seed: 31337
n_shots: [0, 1, 3, 7, 15, 31, 63, 127, 255, 511]
max_length_per_example: 256
max_eval_samples: 250
override_existing_runs: false

model: WangResearchLab/Yarn-Llama-2-7b-128k

vllm:
  tensor_parallel_size: 2
  dtype: bfloat16
  seed: ${global_seed}
  enable_prefix_caching: True